### PR TITLE
several assorted changes to frontend and api

### PR DESCRIPTION
**Pull request by ricardogsilva**
This commit includes too many changes (sorry about that):

- Added a new `PrivilegedUserProfile`, and its registration flow stuff (urls, views, templates)

  This means that privileged users can now register via the portal. Admin notification is not implemented yet, but the rest is functional. When a user chooses to register as a privileged user its account is marked as disabled in keycloak and the user will be unable to use the portal (or the API) until an admin re-enables the account and adds the user to the privileged_users group (this group needs to be created on the Keycloak server)

  User registration:
  privileged_user_registration

  Admin approval:
  privileged_user_admin_approval

- tweaked access permissions for API views. Some API endpoints are now only available to users that are of the correct type. For example, the privileged users can access the `/bikes` endpoint, where they are allowed to inspect all bikes while the normal end users cannot access this endpoint, but have access to a `/my-bikes` endpoint, where they see only their own bikes. In the future, there will be two layers of access control, one for accessing the API endpoints (as it is working now) and another that selects the appropriate data serializer according to the user type (e.g. an analyst user may be able to access the `/bikes` endpoint but might not see info on bikes' physical tags)  

- added new API views

- completed integration with `drf-oidc-auth`. In addition to the `/api/swagger` endpoint, which shows a browser based UI for interacting with the API (that relies on a session based login), it is now possible to access the API in standalone mode. That can be achieved by making a first request to keycloak in order to obtain an access token and then making a second request to the portal's `api/` endpoints and providing the token. Something like:

  ```bash
  # This script demonstrates how to interact with the smb-portal's REST API
  # It requires cURL and jq to be available on the system

  set -e
  set -o pipefail

  REALM="demo"
  CLIENT_ID="demoapp"
  KEYCLOAK_BASE_URL=http://10.0.1.164:8180
  TOKEN_ENDPOINT=${KEYCLOAK_BASE_URL}/auth/realms/${REALM}/protocol/openid-connect/token
  USERNAME=priv1
  PASSWORD=123456

  # 1. Obtain access token
  TOKEN=$(\
      curl \
          --silent \
          --show-error \
          --data "client_id=${CLIENT_ID}" \
          --data "grant_type=password" \
          --data "username=${USERNAME}" \
          --data "password=${PASSWORD}" \
          ${KEYCLOAK_BASE_URL}/auth/realms/${REALM}/protocol/openid-connect/token \
          | jq --raw-output ".access_token"\
  )
  # 2. Make a request to the portal api
  http http://10.0.1.164:8000/api/bikes/ "Authorization: bearer ${TOKEN}"
  ```

  The credentials shown on this script are only valid on my own (offline) dev setup.

- added a KeycloakManager class to interface with the Keycloak server REST API. This is in `keycloakauth.keycloakadmin`. It is used to communicate perform administrative tasks on keycloak, such as disabling users, adding a user to a group, etc.

- added custom rest-framework permissions class for working with django-rules

- tweaked messages section in the base template

- tweaked home template

- updated oidc hook function to sync django groups with keycloak

- added a new templatetag to allow concatenation of strings

- changed the `phone_number` field on the `EndUSerProfile` model to be a
  regex-validated CharField.

- removed unused avatar_field on the EndUserProfile model. Avatars are managed
  with django-avatar

- tweaked the bike_detail template in order to integrate an initial version of
  a gallery for bike pictures (needs more work)

- added more permission rules for bikes and profiles

### CODE REVIEW

**Comment by giohappy** [comment]
Cool! Could you write a note about the specific client settings required to enable admin-client and API client (not admin)? Maybe we could write them in a comment or two in code or settings?

**Comment by ricardogsilva** [comment]
Sure

I've been meaning to add an automated way of configuring the keycloak server so that it is fully reproducible. Haven't had the time to implement it yet because the keycloak admin REST API is a bit qwirky.

I'll provide a textual description in the meanwhile

**Comment by giohappy** [comment]
What about using the [export / import feature](https://www.keycloak.org/docs/latest/server_admin/index.html#_export_import)?

**Comment by ricardogsilva** [comment]
export/import seems like a nice feature, but I'd prefer to have a way to generate a clean configuration for keycloak. My own current setup is rather dirty, with lots of experiments and settings that are not relevant.

However, a good strategy might be to do an export and then tweak the generated json file(s) in order to remove unneeded stuff.

**Pull request merged**
