### PR TITLE
added the vehiclemonitor app with the BikeObservation model

### PR DESCRIPTION
**Pull request by ricardogsilva**
This PR adds a new `vehiclemonitor` app, containing the `BikeObservation` model. This model has the following fields:

- `bike` (foreign key to Bike)
- `reporter` (foreign key to SmbUser)
- `position` (geodjango PointField)
- `created_at` (datetime, automatically assigned when instance is created)
- `observed_at` (datetime, defaults to the current time, but can be changed)
- `details` (additional textual details)

Some additional changes resulting from the inclusion of the new observation model:

- `vehicles.models.CollectedPoint` does not need an owner field since collected points are grouped in `Track`s and a track already has an owner
- added a `get_latest_observation()` method to the `Bike` model in order to easily retrieve a bike's latest observation

### CODE REVIEW

**Comment by ricardogsilva** [comment]
I've made some changes, as requested:

- Added an `address` field to `BikeObservation`. One of `address` or `position` must be provided when creating new instances

- Refactored the bike status stuff

  - Renamed model to `BikeStatus` (previously was called `BikePossessionHistory`). This change led to quite a lot of small changes to the names of related views, serializers, urls, etc.
  - Changed the way the status is recorded. Previously there was a `status` field which allowed a predefined list of statuses. There is now a `lost` boolean field, since we have decided to

    - disallow any all users from changing this attribute, except for the owner. This means that it makes not sense to have a `found_by_third_party` status
    - remove the `stolen` status and keep only the more generic `lost`

  This means that a bike can only be in one of two states: `lost` or `not lost`

**Comment by giohappy** [comment]
It seems there are conflicts

**Comment by ricardogsilva** [comment]
??

That is wierd. I'll review them tomorrow morning then - probably I've goofed something up

**Comment by ricardogsilva** [comment]
I've rebased on top of the dev branch and conflicts were automatically solved, so we're good now

**Pull request merged**
